
public enum EFacilityType
{
    None,
    StageTheme_01,
    StageTheme_02,
    StageTheme_03,
    StageTheme_04,
    StageTheme_05,
    MainBuilding_01,
    MainBuilding_02,
    MainBuilding_03,
    MainBuilding_04,
    MainBuilding_05,
    Resource_Wood,
    Resource_Rock,
    Resource_Steel,
    Sales,
    Wood,
    Rock,
    Steel,
    WorkerUpgradeArea_Log,
    WorkerUpgradeArea_Stone_Brick,
    WorkerUpgradeArea_Silver_Bar,
}